"""Base definitions for agents in the multi-agent Q&A system."""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List


@dataclass
class AgentResponse:
    """Represents a response generated by an agent."""

    content: str
    reasoning: List[str]
    metadata: Dict[str, Any] | None = None


class Agent(ABC):
    """Abstract base class that all concrete agents must extend."""

    name: str

    def __init__(self, name: str) -> None:
        self.name = name

    @abstractmethod
    def handle(self, message: str, context: Dict[str, Any] | None = None) -> AgentResponse:
        """Process the provided message and optional context."""

